executors:
  darwin-linux-no-cgo-java-11:
    docker:
      - image: palantirtechnologies/go:go-darwin-linux-no-cgo-1.13.4-java-11-t28
    working_directory: /go/src/github.com/palantir/godel-conjure-plugin
  darwin-linux-no-cgo-java-11-ir-gen-cli-bundler:
    docker:
      - image: palantirtechnologies/go:go-darwin-linux-no-cgo-1.13.4-java-11-t28
    working_directory: /go/src/github.com/palantir/godel-conjure-plugin/ir-gen-cli-bundler

excutor: &executor
  executor: darwin-linux-no-cgo-java-11

version: 2.1

orbs:
  go: palantir/go@0.0.14
  godel: palantir/godel@0.0.14

all-tags-filter: &all-tags-filter
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  verify-test-dist-publish:
    jobs:
      - godel/verify:
          name: ir-gen-cli-bundler-verify
          checkout-path: /go/src/github.com/palantir/godel-conjure-plugin
          include-tests: true
          executor: darwin-linux-no-cgo-java-11-ir-gen-cli-bundler
      - godel/verify:
          name: verify
          <<: *executor
          <<: *all-tags-filter
      - godel/test:
          name: test
          <<: *executor
          <<: *all-tags-filter
      - godel/dist:
          name: dist
          <<: *executor
          <<: *all-tags-filter
      - godel/bintray-publish:
          name: publish
          <<: *executor
          bintray-subject: palantir
          bintray-repo: releases
          bintray-product: godel-conjure-plugin
          requires:
            - ir-gen-cli-bundler-verify
            - verify
            - test
            - dist
          filters:
            tags:
              only: /^v?[0-9]+(\.[0-9]+)+(-rc[0-9]+)?(-alpha[0-9]+)?$/
            branches:
              ignore: /.*/
